image: git.febacapital.com:5050/feba/images/php71:latest

stages:
 - code_quality
 - test
 
code_style:
  stage: code_quality
  script:
    - /usr/local/bin/composer install
    - /usr/local/bin/composer code-style

static_analysis:
  stage: code_quality
  script:
    - /usr/local/bin/composer install
    - /usr/local/bin/composer code-analysis

testing:
  stage: test
  script:
    - /usr/local/bin/composer install
    - /usr/local/bin/composer test