image: git.febacapital.com:5050/feba/images/php71:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - composer.lock

stages:
 - preparation
 - code_quality
 - test
 
composer:
  stage: preparation
  script:
    - /usr/local/bin/composer install --no-plugins --no-scripts

code_style:
  stage: code_quality
  dependencies:
    - composer
  script:
    - vendor/bin/phpcs --encoding=UTF-8 --error-severity=1 --warning-severity=8 --report=full --report-width=75 --tab-width=4 -p --report=json .

static_analysis:
  stage: code_quality
  dependencies:
    - composer
  script:
    - vendor/bin/phpstan analyze . -c phpstan.neon --level=1 --memory-limit=-1 --no-progress -vvv

testing:
  stage: test
  script:
    - /usr/local/bin/composer install
    - /usr/local/bin/composer test